export interface CountryData {
    code: string;
    name: string;
    dial: string;
}

export const countries: CountryData[] = [
    // ==================== جميع الدول العربية (22 دولة) ====================
    { code: "sy", name: "سوريا", dial: "+963" },
    { code: "jo", name: "الأردن", dial: "+962" },
    { code: "iq", name: "العراق", dial: "+964" },
    { code: "lb", name: "لبنان", dial: "+961" },
    { code: "ps", name: "فلسطين", dial: "+970" },
    { code: "ye", name: "اليمن", dial: "+967" },
    { code: "kw", name: "الكويت", dial: "+965" },
    { code: "qa", name: "قطر", dial: "+974" },
    { code: "bh", name: "البحرين", dial: "+973" },
    { code: "om", name: "عُمان", dial: "+968" },
    { code: "eg", name: "مصر", dial: "+20" },
    { code: "sd", name: "السودان", dial: "+249" },
    { code: "ly", name: "ليبيا", dial: "+218" },
    { code: "tn", name: "تونس", dial: "+216" },
    { code: "dz", name: "الجزائر", dial: "+213" },
    { code: "ma", name: "المغرب", dial: "+212" },
    { code: "mr", name: "موريتانيا", dial: "+222" },
    { code: "so", name: "الصومال", dial: "+252" },
    { code: "dj", name: "جيبوتي", dial: "+253" },
    { code: "km", name: "جزر القمر", dial: "+269" },
    { code: "sa", name: "المملكة العربية السعودية", dial: "+966" },
    { code: "ae", name: "الإمارات العربية المتحدة", dial: "+971" },
    // ==================== أوروبا ====================
    { code: "tr", name: "تركيا", dial: "+90" },
    { code: "gb", name: "المملكة المتحدة", dial: "+44" },
    { code: "de", name: "ألمانيا", dial: "+49" },
    { code: "fr", name: "فرنسا", dial: "+33" },
    { code: "it", name: "إيطاليا", dial: "+39" },
    { code: "es", name: "إسبانيا", dial: "+34" },
    { code: "ru", name: "روسيا", dial: "+7" },
    { code: "nl", name: "هولندا", dial: "+31" },
    { code: "be", name: "بلجيكا", dial: "+32" },
    { code: "ch", name: "سويسرا", dial: "+41" },
    { code: "at", name: "النمسا", dial: "+43" },
    { code: "se", name: "السويد", dial: "+46" },
    { code: "no", name: "النرويج", dial: "+47" },
    { code: "dk", name: "الدنمارك", dial: "+45" },
    { code: "fi", name: "فنلندا", dial: "+358" },
    { code: "pl", name: "بولندا", dial: "+48" },
    { code: "gr", name: "اليونان", dial: "+30" },
    { code: "pt", name: "البرتغال", dial: "+351" },
    { code: "ie", name: "أيرلندا", dial: "+353" },
    { code: "cz", name: "التشيك", dial: "+420" },
    { code: "ro", name: "رومانيا", dial: "+40" },
    { code: "hu", name: "المجر", dial: "+36" },
    { code: "ua", name: "أوكرانيا", dial: "+380" },

    // ==================== آسيا والأوقيانوسيا ====================
    { code: "jp", name: "اليابان", dial: "+81" },
    { code: "cn", name: "الصين", dial: "+86" },
    { code: "kr", name: "كوريا الجنوبية", dial: "+82" },
    { code: "in", name: "الهند", dial: "+91" },
    { code: "pk", name: "باكستان", dial: "+92" },
    { code: "bd", name: "بنجلاديش", dial: "+880" },
    { code: "id", name: "إندونيسيا", dial: "+62" },
    { code: "my", name: "ماليزيا", dial: "+60" },
    { code: "sg", name: "سنغافورة", dial: "+65" },
    { code: "th", name: "تايلاند", dial: "+66" },
    { code: "vn", name: "فيتنام", dial: "+84" },
    { code: "ph", name: "الفلبين", dial: "+63" },
    { code: "ir", name: "إيران", dial: "+98" },
    { code: "af", name: "أفغانستان", dial: "+93" },
    { code: "az", name: "أذربيجان", dial: "+994" },
    { code: "ge", name: "جورجيا", dial: "+995" },
    { code: "kz", name: "كازاخستان", dial: "+7" },
    { code: "uz", name: "أوزبكستان", dial: "+998" },
    { code: "au", name: "أستراليا", dial: "+61" },
    { code: "nz", name: "نيوزيلندا", dial: "+64" },

    // ==================== الأمريكتان ====================
    { code: "us", name: "الولايات المتحدة الأمريكية", dial: "+1" },
    { code: "ca", name: "كندا", dial: "+1" },
    { code: "mx", name: "المكسيك", dial: "+52" },
    { code: "br", name: "البرازيل", dial: "+55" },
    { code: "ar", name: "الأرجنتين", dial: "+54" },
    { code: "co", name: "كولومبيا", dial: "+57" },
    { code: "cl", name: "تشيلي", dial: "+56" },
    { code: "pe", name: "بيرو", dial: "+51" },
    { code: "ve", name: "فنزويلا", dial: "+58" },
    { code: "ec", name: "الإكوادور", dial: "+593" },
    { code: "bo", name: "بوليفيا", dial: "+591" },
    { code: "py", name: "باراغواي", dial: "+595" },
    { code: "uy", name: "أوروغواي", dial: "+598" },
    { code: "cu", name: "كوبا", dial: "+53" },
    { code: "cr", name: "كوستاريكا", dial: "+506" },
    { code: "pa", name: "بنما", dial: "+507" },

    // ==================== إفريقيا ====================
    { code: "za", name: "جنوب أفريقيا", dial: "+27" },
    { code: "ng", name: "نيجيريا", dial: "+234" },
    { code: "ke", name: "كينيا", dial: "+254" },
    { code: "gh", name: "غانا", dial: "+233" },
    { code: "et", name: "إثيوبيا", dial: "+251" },
    { code: "tz", name: "تنزانيا", dial: "+255" },
    { code: "ug", name: "أوغندا", dial: "+256" },
    { code: "cm", name: "الكاميرون", dial: "+237" },
    { code: "ci", name: "ساحل العاج", dial: "+225" },
    { code: "sn", name: "السنغال", dial: "+221" },
];