server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    # هذا هو السطر السحري الذي يوجه أي مسار غير موجود إلى ملف index.html ليقوم React بمعالجته
    location / {
        try_files $uri $uri/ /index.html;
    }
}